name: Fetch Futures Daily

on:
  schedule:
    - cron: "0 16 * * *" # 收盘后16: 00运行，试一下使用中国时区
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-timeline:
    runs-on: ubuntu-latest
    env:
      JQDATA_USERNAME: ${{ secrets.JQDATA_USERNAME }}
      JQDATA_PASSWORD: ${{ secrets.JQDATA_PASSWORD }}
      PGURL: ${{ secrets.PGURL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tzdata
        run: sudo apt-get update && sudo apt-get install -y tzdata
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Set timezone
        run: sudo ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        env:
          TZ: Asia/Shanghai

      - name: Verify timezone
        run: date          

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Run script
        run: python -m jqdata_fetcher.tasks.daily
